language: cpp
os: linux
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - clang++-8
      - libgtest-dev
      - libbenchmark-dev
      - libboost-stacktrace-dev
      - cmake

env:
  - BMI2_CMD="-DUSE_BMI2=OFF" MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
  - BMI2_CMD="-DUSE_BMI2=ON" MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
  - BMI2_CMD="-DUSE_BMI2=OFF" MATRIX_EVAL="export CC=clang-8 && export CXX=clang++-8"
  - BMI2_CMD="-DUSE_BMI2=ON" MATRIX_EVAL="export CC=clang-8 && export CXX=clang++-8"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - cp -r /usr/src/googletest .
  - ( cd googletest && cmake . && make -j2 )
  - export CMAKE_LIBRARY_PATH="$PWD/googletest/lib/"

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Release ${BMI2_CMD} -DUSE_NO_EXCEPTIONS=ON ..
  - make -j2
  - ctest
